import '@shadcn-ui/styles/globals.css';

export const metadata = {
  title: 'Welcome to pm-ms-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
